patch/as tactic
uwplse/PUMPKIN-PATCH pull request #69
Opened 2020-01-10 04:28 UTC by randair

Patch proof tactic of the form "patch old new as hyp_name", which behaves as the Patch Proof command does but creates a hypothesis instead. Common patch functionality is refactored.

2020-01-11 00:22 UTC, tlringer requested changes
Glad this is working :). Just a few comments.

In addition, what happens when you run `./build.sh` followed by `./test.sh`? Can you paste the output into here so I can check it?

I would also like to see a few test cases. Those can build on the existing tests. Happy to help with these next meeting if you'd like. Then we can talk about next steps.

2020-01-11 00:22 UTC, tlringer commented on plugin/src/patcher.ml4
>      Printf.printf "Defined %s\n" prefix);
I would move this print statement underneath the place you move define_term

2020-01-11 00:22 UTC, tlringer commented on plugin/src/patcher.ml4
>      Printf.printf "Defined %s\n" prefix);
So I guess inside of the function you pass to the higher-order function

2020-01-11 00:22 UTC, tlringer commented on plugin/src/patcher.ml4
>        invert_patch inv_n env patch sigma
I think you will need to play a similar game here and pass `define` to `invert_patch`, then call it similarly

2020-01-11 00:22 UTC, tlringer commented on plugin/src/patcher.ml4
> +  define sigma patch
In which case, the `define` call here should go before the call to `invert_patch`

2020-01-11 00:22 UTC, tlringer commented on plugin/src/patcher.ml4
> +   application because it messes with the type of "search" *)
I would get rid of this comment, and add a comment here explaining this is the tactic version

2020-01-11 00:22 UTC, tlringer commented on plugin/src/patcher.ml4
> +let patch_command env n try_invert a search sigma =
And I'd add a comment here explaining this is the command version

2020-01-11 00:22 UTC, tlringer commented on plugin/src/patcher.ml4
> +   application because it messes with the type of "search" *)
Plus maybe an explanation of what is different from the command version

2020-01-11 00:22 UTC, tlringer commented on plugin/src/patcher.ml4
> +let patch_proof_tactic n d_old d_new =
Same here, I'd add comments explaining tactic/command version and what the difference is. They can be brief.

2020-01-11 01:41 UTC, randair commented
Oops I left a typo on 137. Fixed and will make the remaining requested changes.

2020-01-11 02:42 UTC, randair commented
Attached is the output of ./build.sh followed by ./test.sh.
[output.txt](https://github.com/uwplse/PUMPKIN-PATCH/files/4048888/output.txt)

2020-01-13 17:06 UTC, tlringer commented
OK, tests look good. Let's take a shot at the PR feedback when you're in, and then we can move on to producing tactics.

2020-01-13 23:09 UTC, tlringer commented on plugin/src/patcher.ml4
>        invert_patch inv_n env patch sigma
Then in the tactic you'll need to define both hypotheses

2020-01-13 23:23 UTC, tlringer requested changes
For regression tests, extend `Regress.v` with dummy proofs that call your tactic. 

Then also extend `divide.v` with a copy of the proof anywhere we use the patch currently to use your tactic, and same with `IntegersNew.v`. That should be enough to start.

2020-01-16 23:02 UTC, tlringer approved these changes
Looks good. We can talk tomorrow about what's next.

2020-01-16 23:03 UTC, merged