Suggest patch tactic
uwplse/PUMPKIN-PATCH pull request #70
Opened 2020-01-24 21:50 UTC by randair

`suggest patch old new`
Currently just prints out `apply "generated patch term"`.
Will push version where the Id names are optional, instead of passing a dummy string to the suggest patch tactic since it doesn't create any new definitions anyway.

2020-01-27 22:39 UTC, tlringer requested changes
Have you tested this out? Otherwise just two comments

2020-01-27 22:39 UTC, tlringer commented on plugin/src/patcher.ml4
> +    let s = Printer.pr_constr_env (Global.env ()) Evd.empty patch in
Using Evd.empty is generally not good. Here you can pass in env and sigma, though it looks like you'll need to make a change to pass env.

2020-01-27 22:39 UTC, tlringer commented on plugin/src/patcher.ml4
> +    Feedback.msg_notice (str "apply " ++ s); last_def),
Sorry if I told you to use the wrong one (I very well may have), but you want `msg_info` rather than `msg_notice` for consistent behavior across IDEs

2020-01-28 00:42 UTC, randair commented
[./build.sh && ./test.sh](https://github.com/uwplse/PUMPKIN-PATCH/files/4120075/output.txt)

2020-02-01 00:24 UTC, tlringer approved these changes

2020-02-01 00:24 UTC, merged